#!/usr/bin/env bash
set -E -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"

RELEASE_PACKAGE_NAME="UniFi Network Controller"
RELEASE_TAG_PACKAGE_NAME="unifi-controller"

UPSTREAM_PACKAGE_NAME="UniFi Network Controller"
UPSTREAM_VERSION_CONFIG_KEY="UNIFI_CONTROLLER_VERSION"

TEST_TYPE="background"
TEST_CONTAINER_TYPE="unifi-controller"
TEST_CONTAINER_START_WAIT_SECONDS="20"

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    local gpg_key_uri="https://dl.ui.com/unifi/unifi-repo.gpg"
    local gpg_key_path="/usr/share/keyrings/unifi.gpg"
    local unifi_repo="https://www.ui.com/downloads/unifi/debian"
    docker run --rm $(base_image_name) sh -c "homelab download-file-as ${gpg_key_uri:?} ${gpg_key_path:?} && (echo 'deb [signed-by=${gpg_key_path:?}] ${unifi_repo:?} stable ubiquiti' > /etc/apt/sources.list.d/unifi.list) && apt-get -qq update >/dev/null 2>&1 && (apt-cache madison unifi | tr -s ' ' | cut -d '|' -f 2 | cut -d ' ' -f 2 | sort --version-sort --reverse | head -1)"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    echo "Updating ${UPSTREAM_PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    git add ${ARGS_FILE:?}
}

package_current_release_version() {
    current_upstream_version
}

test_start_container() {
    local container_name="${1:?}"
    docker run \
        --name ${container_name:?} \
        --detach \
        --rm \
        --publish 127.0.0.1:8082:8443 \
        ${IMAGE:?}
}

test_image_after_container_startup() {
    local container_name="${1:?}"
    test_http_endpoint "${container_name:?}" https-insecure 127.0.0.1 8082 200
}
